# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#warnings_are_errors: true
sudo: required
dist: trusty

# using renv with travis.ci
# https://rstudio.github.io/renv/articles/ci.html

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

#script:
  #- Rscript -e '<your-build-action>'
